### ISSUE TITLE
[Meta issue] - ScrAPD 3.0.0

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapd#191]
Alright people, ScrAPD 3.0.0 is coming bring along the support for multi-fatalities, an improved data set structure, a cleaner code base and much more!

However there are a bunch of moving pieces, so here is the plan of action:
- [x] ~[Matt] Reorganize files: https://github.com/scrapd/scrapd/pull/188~
- [x] [Matt & Rémy] Approve new format: https://github.com/scrapd/scrapd/issues/190
- [x] [Matt] Finalize multi-fatality PR (new format): https://github.com/scrapd/scrapd/pull/184
- [x] [Rémy] Convert scrapd 2 to scrapd 3: https://github.com/scrapd/datasets/issues/60 -> https://github.com/scrapd/datasets/pull/62 
- [x] [Rémy] Validate pipeline & tooling: https://github.com/scrapd/datasets/issues/61
- [x] [Rémy] Update ScrAPDviz queries: https://github.com/scrapd/scrapdviz/issues/148

A new home page for the dashboard is coming soon, so I am super pumped about this update. Stay tuned!
